server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-server
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          # ?? ??? ?? ???? ??? ?? ? ??? URL
          uri: https://github.com/cordingkid/config-repo
          # ??? ? ??? ?? ????? main ????? ?? ???? ????.
          default-label: main
          # ?? ??? ?? ?? ??
          timeout: 5
          # ??? ??? ??? ???? ???? ??? ??
          clone-on-start: true
          # ?? ???? ?? ???? ?? ?? ??? ?? ?????? ????
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true